### ISSUE TITLE
if any excuse A else B can not work in the latest comfyui(sovled)

### ISSUE THREAD

**Issue by qinxiaotao** [edenartlab/eden_comfy_pipelines#17]
if any excuse A else B can not work in the latest comfyui,no this node 

![if](https://github.com/user-attachments/assets/1fb11f95-6749-46c5-99ae-f58585a3fa8c)

**Comment by iamargentum** [comment]
facing the same issue
ComfyUI manager displays a warning after installing the node
![image](https://github.com/user-attachments/assets/e4bd54a0-85e9-40d8-b498-a054f3cbefe3)
could this be the reason for it not working?

**Comment by qinxiaotao** [comment]
after update latest version,solved
