### ISSUE TITLE
There are two nodes that are unavailable, please see the video feedback for details.

### ISSUE THREAD

**Issue by wibur0620** [edenartlab/eden_comfy_pipelines#3]
https://github.com/edenartlab/eden_comfy_pipelines/assets/131615326/90d9f32d-ec23-48e9-8218-90a7f780c337

[ComfUI.txt](https://github.com/edenartlab/eden_comfy_pipelines/files/14002142/ComfUI.txt)

**Comment by aiXander** [comment]
yeah this is my mistake, these nodes arent ready yet I will remove them for now! Will be added soon, thx for informing me :)
